name: nextmind_mobile_v2
description: "Nova versão do aplicativo mobile do projeto integrador NextMind."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_injector: ^2.1.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  logger: ^2.6.1
  result_dart: ^2.1.1
  routefly: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
